name = "blog"
main = "src/worker.ts"
compatibility_date = "2023-06-02"


[[d1_databases]]
binding = "D1"                                       # i.e. available in your Worker on env.DB
database_name = "blog"
database_id = "0f579a5b-6481-4eee-bcea-fbaad36923b3"
migrations_dir = "./drizzle"
migrations_table = "__drizzle_migrations"
